# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-23 11:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0002_product_image_back'),
    ]

    operations = [
        migrations.CreateModel(
            name='BtcInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100, null=True)),
                ('price_in_usd', models.DecimalField(decimal_places=8, max_digits=15)),
                ('price_in_btc', models.DecimalField(decimal_places=8, max_digits=15)),
                ('added_time', models.DateTimeField(default=datetime.datetime.now)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Order')),
            ],
            options={
                'get_latest_by': 'added_time',
            },
        ),
        migrations.RunSQL(
            "INSERT INTO btc_payment_btcinvoice (invoice_id, address, price_in_usd, price_in_btc, added_time) VALUES (9999, '1Pjc6NVTqFWQa6bj8HE1n3mU5nBgCty8WN', 99, 0.99, '2018-04-20 16:20:20');"
        ),
        migrations.CreateModel(
            name='BtcInvoicePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(max_length=150, null=True)),
                ('value', models.PositiveIntegerField(help_text='must be devided by 100000000')),
                ('invoice', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='btc_payment.BtcInvoice')),
            ],
        ),
        migrations.CreateModel(
            name='BtcPendingInvoicePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=15)),
                ('transaction_hash', models.CharField(max_length=150, null=True)),
                ('value', models.PositiveIntegerField(help_text='must be devided by 100000000')),
            ],
        ),
    ]
