# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-29 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='lead',
            field=models.TextField(blank=True, null=True, verbose_name='Lead Paragraph'),
        ),
    ]
