# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-10 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_homepage_featured_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='footer_address',
            field=models.TextField(default='Our address', help_text='Company address displayed on footer.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_subscribe_info',
            field=models.CharField(default='Pellentesque habitant morbi tristique senectus et netus \t\t\t\tet malesuada fames ac turpis egestas.', help_text='Text displayed above the subscribe field.', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='blog_subheading',
            field=models.CharField(default="What's new in the world of fashion?", help_text='A subheader displayed above blog entries', max_length=100),
        ),
        migrations.AlterField(
            model_name='iconblurb',
            name='link',
            field=models.CharField(blank=True, help_text='Optional, if provided clicking the blurb will go here.', max_length=200),
        ),
    ]
