# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-28 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180427_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqpage',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faqpage',
            name='subheader',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
