# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-06 09:49
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_back',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Additional Image'),
        ),
    ]
